// Add any additional repositories for your dependencies here.

repositories {
	mavenLocal()
    maven {
        url = "https://nexus.gtnewhorizons.com/repository/releases/"
    }
    maven {
        url = "https://nexus.gtnewhorizons.com/repository/maven_cil_li/"
    }
    maven {
        url = "https://repo.maven.apache.org/maven2/"
    }
    maven {
        url = "https://gregtech.overminddl1.com/"
    }
    mavenCentral()
}
